### ISSUE TITLE
Setting up a development environment

### ISSUE THREAD

**Issue by sofiaritz** [marcua/ayb#213]
I'm working on a simple UI for ayb, and I've encountered some problems:
1. The [ayb.toml in the README](https://github.com/marcua/ayb#running-a-server) is out-of-sync with [the actual definition](https://github.com/marcua/ayb/blob/afef0da9077699cafb95df0776f55631be3f3fb8/src/http/structs.rs#L24).
2. I'm not really sure how to fill the SMTP config in a dev environment.
3. I'm not really sure what `fernet_key` refers to.

I think it could be a good idea to link the ayb.toml definition in the readme with a notice that the example may be out of sync (example: https://git.sofiaritz.com/Infrastructure/status-page#with-docker-compose-recommended).

I don't think the creation of extensive documentation at such an early development stage is necessarily a good idea, maybe a pinned issue is better right now for documenting changes to the development environment.

Thank you in advance :)

**Comment by marcua** [comment]
I'm sorry for this unwelcoming introduction to `ayb` @sofiaritz ! Thank you for reporting the issue you ran into getting started. I hurt the documentation on points 2 & 3 with the introduction of #145. My intention was to resolve it with #143 and #142 (the combination would have made an `ayb.toml` be automatically generated with reasonable defaults). Having not implemented those, I left you in a bad spot. Until they exist, here's an explanation:
* To your point, ultimately we'll want to provide a non-SMTP way to test the registration flow in dev. There are two ways to approach this:
  * You can imagine that, in addition to having a way to register accounts with authentication over email, we have a dev-only way to register with authentication messages going to the console. The solution for this can live almost entirely in [this file](https://github.com/marcua/ayb/blob/main/src/email.rs), by offering an `AybConfigEmail` option that prints to the console.
  * As a temporary and hacky alternative, you can use the trick I employ in [end-to-end tests](https://github.com/marcua/ayb/blob/main/tests/e2e.rs#L101), where I wrote a little SMTP server stub that writes emails to disk. If you run that stub SMTP server locally and provide its connection details in `ayb.toml`, that should do the trick.
* The `fernet_key` is the unique-to-you ayb.toml secret key we use for generating the encrypted token we send in registration emails. It uses the [fernet library](https://docs.rs/fernet/latest/fernet/), and you can generate a key with `fernet::Fernet::generate_key();` (though the [Python version](https://cryptography.io/en/latest/fernet/#cryptography.fernet.Fernet.generate_key) might be simpler to run at the command line). In the #143 implementation I envision, this would get generated for you automatically if it's not already provided.

These responses are just available to get you temporarily unblocked. I'm sorry again for the rough welcome, and would be happy to help you come up with temporary solutions that work for you.

I'm excited to hear about a UI for ayb! What a delightful and welcome idea. I can't wait to hear more!

**Comment by sofiaritz** [comment]
> To your point, ultimately we'll want to provide a non-SMTP way to test the registration flow in dev

Maybe an option to disable e-mail sending altogether would be useful for some users who do not have access to SMTP servers. [My Forgejo instance is set-up like that](https://forgejo.org/docs/latest/admin/email-setup/) because I don't want to deal with having to monitor my SMTP server for spam, having to contact support to open the ports, etc.
When a Forgejo/Gitea server is set-up like that, the [account recovery page](https://git.sofiaritz.com/user/forgot_password) is just a page telling the user that e-mail based account recovery is disabled and that they should contact the instance admin.

The registration flow could be similar (although a different flow where the token is directly returned in those cases would be better), but instead of sending the confirmation token to the e-mail, it could be sent in the response. While it's true that this would mean that no e-mail would be _truly_ verified, this is up to the instance administrator to manage.

> If you run that stub SMTP server locally and provide its connection details in ayb.toml, that should do the trick.

I've got the `ayb` server and the SMTP stub running, everything is working fine :)

> I'm excited to hear about a UI for ayb! What a delightful and welcome idea. I can't wait to hear more!

The idea is to create a web-based UI that supports multiple profiles for different instances, listing databases, and most importantly querying and modifying databases :)

Thank you for your help, you can expect a few PRs and issues as I start working on the UI :p

**Comment by marcua** [comment]
> Maybe an option to disable e-mail sending altogether would be useful for some users who do not have access to SMTP servers. 

This makes sense. I'm trying to figure out if the right way to implement this is to change the response type of the registration endpoint or to simply print what the email would say to the console. I like printing to the console because it keeps the API the same regardless of the server's mechanism of communicating outside of the API, and the implementation is relatively simple.

> I've got the `ayb` server and the SMTP stub running, everything is working fine :)

Hooray!

> The idea is to create a web-based UI that supports multiple profiles for different instances, listing databases, and most importantly querying and modifying databases :)

This is great! I noticed CORS in your other PR, and it made me wonder how the API would be called from the browser (which typically doesn't have access to API keys/secrets, and instead usually has some sort of session-based authentication). Perhaps while you're prototyping the web-based UI, we can in parallel discuss these details on an issue dedicated to it. I've created #216 to this effect. I'm excited for this project!

**Comment by marcua** [comment]
I just merged #223, which will hopefully make it easier for anyone trying out `ayb` and prevent future configuration misalignment. Thank you so much for sharing your notes on getting started @sofiaritz ! You've made it so much better for future users! :)

**Comment by sofiaritz** [comment]
That's great news!! :)
