### ISSUE TITLE
A web frontend for `ayb`

### ISSUE THREAD

**Issue by marcua** [marcua/ayb#216]
Some open questions
* How should authentication with the API happen? Do we need session-based auth, or is there a way to rely on the API keys/secrets?
* Can each `ayb` instance host its own web frontend, or is the web frontend project distinct from `ayb`?

**Comment by sofiaritz** [comment]
> I worry a little bit that the loose coupling (...) will add complexity to a new user's mental model as they try to understand ayb

From the perspective of a new user, there are instances with an UI and instances that "only" work with the CLI. A new user doesn't need to understand the relationship between ayb, the CLI, and webAyb.

> The bigger threat to aybWeb and ayb right now is not finishing the v1 of each (...)

hahaha, exactly :)

> We should differentiate between the authentication method (...) from the proof of authentication

Yeah, I got things mixed up there :p

---

About storing and returning the secret I think there are two paths we can take:
1. The Cookie route
    * The servers sets the cookie directly (I like `ayb_sessionid`), that cookie should be both [HttpOnly and with SameSite set to Strict](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security) and potentially encrypted by the server.
    * This means that #214 should still be implemented.
    * This also adds some coupling between frontends and servers because there are now two kinds of authentication proofs: Bearer tokens and cookies (only for web-based clients).
2. The `Authorization` route
     * The server returns a list of authentication proofs ([example](https://git.sofiaritz.com/sofia/gists/src/branch/main/0000-ayb-example-auth-list.md)), then each client decides which one to use. Every client would use the `Authorization` header, maybe with a prefix to help the server identify the kind of token ([example](https://git.sofiaritz.com/sofia/gists/src/branch/main/0001-ayb-example-auth-header.md)).
     * This means #214 doesn't necessarily need to be implemented because the JWT already contains the data.
         * JWT doesn't encrypt the payload, instead it adds a signature that the server can check. This means that the JWT *both* serves as an authentication proof and as a data container.
     * In contrast with the Cookie route, the server only needs to check the `Authorization` header, which also prevents edge cases related to receiving a request with *both* a cookie and a header, and things like that.

I prefer the second one (with or without JWT), but I want to hear your thoughts on those two options :)

**Comment by sofiaritz** [comment]
Unrelated to the current discussion, but related to the web frontend: what is your vision for this web frontend? I just implemented a simple frontend with the endpoints I had available and a few assumptions I made :)

A more GitHub-like experience would require different endpoints and UI/UX decisions than a PlanetScale-like experience :p
I know that you are more inclined towards a GitHub-like experience.

**Comment by marcua** [comment]
Re: cookie vs. authorization: I agree that the authorization route looks cleaner, but I'm (probably being silly and) stuck on one conceptual thing: how would a browser store the token? The bearer auth token setups I've seen have all been for cases where a backend stores a token/secret and attaches it to HTTP requests. In the case of a browser that I log into, don't I need to store a cookie so that when I reload or close the browser, the session/cookie is maintained?

Re: the web frontend
* I have a lot of thoughts on the frontend, but my primary one is that the v1 you created is infinity times better than the non-existent one we have today! :) It also matches the current state of the backend and data models, which will expand with time.
* I'm an incrementalist, and think that the experience you have for an entity (show the databases, drill into a database, query the database, eventually share the database with others) is the right one, and we can expand from there.
* Not to keep any secrets, the reason I envision a GitHub-style experience is that it will ultimately allow discovery/exploration/collaboration, where you can find people who are interested in similar datasets as you (e.g., "We all live in city X, and are building a collection of datasets for that city"). The limiting factor here is the backend: in order to realize the longer-term vision on the web frontend, we'll need to first add access control, sharing, publicly read-only access, organizations, and the ability to list entities, to name a few. :)

**Comment by sofiaritz** [comment]
> how would a browser store the token?

[localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). That's the way it is implemented right now in my WIP frontend, and I have deployed various services whose APIs use the `Authorization` header and the frontend stores the token in localStorage :)

> my primary one is that the v1 you created is infinity times better than the non-existent one we have today! :)

Hahaha, thank you :))

> and think that the experience you have for an entity (...) is the right one, and we can expand from there.

That's great to hear!

Re: GitHub-like experience. Alright, I think I fully understood the idea now. I'll do some prototyping around some GitHub-esque UI tailored to the "database-style". I think that having things like the ability to run non-destructive queries on public databases could be nice... I'll do some testing on my fork and report back to you :)

**Comment by marcua** [comment]
> localStorage. 
No problem if it works for the v1, but when I've seen localStorage used, it's been more for "runs entirely in the browser, copy/paste a token here"-style experiences. I've seen more sessions/cookies for browser-based auth, but I don't think any of this is a blocker to prototyping the concept regardless. For what it's worth, I suspect the existing API is fine if the intention is to store an API key in localStorage.

One detail this is making me realize is that we'd have to figure out (regardless of key management) is how to tell ayb to send a confirmation URL to aybWeb via email rather than a command line confirmation link. Would be easier with tight coupling, but nothing a little configuration/templating can't fix :).

> I'll do some prototyping around some GitHub-esque UI 
This is amazing, but don't feel pressure to get it all done in a v1. That said, the read-only queries thing is exciting, and I was hoping to make progress on public read-only access in the API after figuring out some details about isolation (#41).

**Comment by sofiaritz** [comment]
> I was hoping to make progress on public read-only access in the API after figuring out some details about isolation

That's great! Keep me updated :)

> but when I've seen localStorage used, it's been more for "runs entirely in the browser, copy/paste a token here"-style experiences

Not at all! localStorage is very useful for non web specific APIs. The following diagram describes a complete log-in and authenticated action sequence that works just like a cookie-based website from the perspective of the user.

I haven't implemented a login page based on email-password credentials in aybWeb because that endpoint doesn't exist yet, but the idea is to implement that before the initial public release.
```mermaid
sequenceDiagram
    User->>Frontend: Log-in info (username, e-mail, password, etc)
    Frontend->>API: Log-in info
    API->>API: Create a token
    API->>Frontend: Send the token back
    Frontend->>Frontend: Store the token in localStorage
    Frontend-->User: Redirect the user outside the login page
    User->>Frontend: Run authenticated action
    Frontend->>Frontend: Retrieve the token from localStorage
    Frontend->>API: Request to run authenticated action, sends the token
    API->>API: Check that the token is valid
    API->>API: Run action
    API->>Frontend: Return the result of the action
    Frontend-->User: Display the result
```

**Comment by marcua** [comment]
That's a very helpful diagram, thank you! Given you've got things working end-to-end, I propose we not spend time on another session/authentication mechanism just yet. If anyone wants to build a web frontend that doesn't live entirely in the browser, or if we ever want to support expiring keys, we can revisit it at that point. I feel like the remaining loose end is the first portion of your diagram:

sequenceDiagram
    User->>Frontend: Log-in info (username, e-mail, password, etc)
    Frontend->>API: Log-in info
    API->>API: Create a token

Right now, when the frontend calls the API to register, the user gets an email with a short-lived confirmation token. The email says to use the command line to confirm the registration. We'll want `ayb` to optionally offer another (templated) way to add the confirmation token to a URL (e.g., "To complete your registration, visit https://ayb.sofiaritz.com/confirm/{token}"). One idea is to support an optional confirmation template string that defaults to the command line confirmation instruction but can be configured in `ayb.toml` to send the user elsewhere. When the frontend receives a request at that URL, it sends it to the API, and gets access to the token. Voila!

**Comment by sofiaritz** [comment]
> One idea is to support an optional confirmation template string that defaults to the command line confirmation instruction but can be configured in `ayb.toml` to send the user elsewhere

I like the idea :)

Something like this:
```toml
[email.templates.login]
confirmation_url = "https://ayb.sofiaritz.com/confirm/{token}"
```

That would allow us to do things like this in the future:
```toml
[email.templates]
footer = "<a href=\"https://github.com/marcua/ayb\">ayb</a> · <a href=\"mailto:sofi@sofiaritz.com\">Support</a>"

[email.templates.login]
confirmation_url = "https://ayb.sofiaritz.com/confirm/{token}"

[email.templates.reset_password]
reset_url = "https://ayb.sofiaritz.com/reset/{token}"
```

**Comment by marcua** [comment]
Now that you have it all working, I'm going to resolve this issue, but feel free to re-open if we need to think through the design more. Thank you for making this happen! :)
