### ISSUE TITLE
Make build fail on clippy checks

### ISSUE THREAD

**Issue by marcua** [marcua/ayb#250]
We run `clippy` as part of GH actions, but don't break the build if it finds opportunities.

* Add `--no-deps` so we don't lint other packages: `cargo clippy --no-deps`
* Make it fail if there are any warnings (there currently are, so we'll have to fix them as well).

**Comment by sofiaritz** [comment]
> there currently are, so we'll have to fix them as well

Are there? I run `cargo clippy --fix` and also fix the non-machine applicable problems before pushing to my feature branches.

> Make it fail if there are any warnings

We need to replace https://github.com/marcua/ayb/blob/7bcd087028b86e1dcce4b552263ff6a5ba186293/.github/workflows/tests.yml#L39 with ```cargo clippy -- -D warnings``` to fix that

**Comment by marcua** [comment]
> Are there?
Luckily not on `main` --- I introduced some in #41 but luckily caught them before merging :)

>We need to replace
Perfect! I'll test that it properly breaks the build and get it shipped! Thank you!

**Comment by marcua** [comment]
It worked! Thank you!
