### ISSUE TITLE
Return entity slug with confirmation endpoint

### ISSUE THREAD

**Issue by marcua** [marcua/ayb#260]
This would allow frontends to redirect the user to their profile after logging in

**Comment by sofiaritz** [comment]
After some feedback from [@Sugui@awoo.fai.st](https://awoo.fai.st/users/Sugui) we're now N=3. I'll work on this next week if I have time to do so :)

**Comment by marcua** [comment]
Wonderful validation! Thank you so much @sofiaritz and @Sugui@awoo.fai.st! :)
