### ISSUE TITLE
Slugs with uppercase characters makes some endpoints fail

### ISSUE THREAD

**Issue by sofiaritz** [marcua/ayb#266]
The entity retrieval endpoint returns `RecordNotFound` when the given slug contains any uppercase character.
I think we should disallow slugs with uppercase characters altogether to prevent confusion and possible abuse (`admin` ≠ `Admin` internally but may mislead people).

Users can change their display name anyways.
Thanks @Suguivy for discovering this issue!

**Comment by marcua** [comment]
Thank you so much @sofiaritz for submitting and @Suguivy for testing and discovering the issue!

We should definitely address this. There might even be a subtle security vulnerability here, though its minor and our longer-term plan is to make the leaked information public. Some thoughts:
* On the registration endpoints, we explicitly [lowercase usernames and emails when they are passed in as headers](https://github.com/marcua/ayb/blob/main/src/http/endpoints/register.rs#L19)
* In the entity retrieval endpoint, [we don't modify the entity slug from the URL](https://github.com/marcua/ayb/blob/main/src/http/endpoints/entity_details.rs#L22). We likely want similar lowercasing logic there.
* The solution to this issue stops at the previous bullet. That said, the subtle security issue is that the entity details endpoint checks whether `can_query(&authenticated_entity, v)`, but not whether the authenticated entity can actually access the profile details of `desired_entity`. This is minor: we intend to make the profile information publicly accessible once we have better access control for private vs. public databases.

**Comment by marcua** [comment]
I've started working on this, first by updating tests for the sensitive endpoints. I'll submit a crude fix in the coming days so we can come up with a more elegant/implicit one.

**Comment by marcua** [comment]
PR #269 resolves the reported issue (and caught a tiny bug as well). While I'd like to ship the fix, the solution raises a few questions
* We now manually lowercase the entity slug from each path. That's not resilient for the next endpoint, where we'll ostensibly have to remember to do the same thing. Ideally entity paths would be lowercased automatically, perhaps inside of `EntityPath` or something like that?
* Should database names/slugs be case-insensitive as well? There's an argument to be made in both directions: 1) consistency in casing suggests we should make them all case-insensitive, vs. 2) database names are file names, which respect casing at least on Linux. I initially made entity names lowercased on creation to make things like remembering your username and avoiding similar usernames simpler, which doesn't apply as much to database names.

**Comment by sofiaritz** [comment]
Re: databases names, I also lean towards maintaining the status quo there.

About how should we approach the lowercasing, I think the best way is to create a struct like `LowercaseString` that implements `From<String>` and `FromStr` and that can be used in the [database models](https://github.com/marcua/ayb/blob/f6022919e110e4087898ac6044e784fc9f6b9589/src/ayb_db/models.rs#L216) to ensure that everything that goes into the database is lowercased. That would require implementing the `Serialize` and `Deserialize` traits manually, but I think we already do that somewhere and this isn't really complex to implement tbh.

We should also implement the [`Defer` trait](https://doc.rust-lang.org/std/ops/trait.Deref.html) to automagically convert `LowercaseString` into a `&str`, this usually isn't a best practice (generally this is a really bad idea because implicit conversions are mostly undesired), but the [`String` type does this](https://doc.rust-lang.org/src/alloc/string.rs.html#2530) which means that we probably should too.

I also think that we should land the current PR and work on improving the current state in the near future :)

**Comment by marcua** [comment]
Great thinking, @sofiaritz! I've merged the #269, and will copy/paste your advice on the cleaner solution into a new issue. Thank you so much @sofiaritz and @Suguivy!
