### ISSUE TITLE
Rename Entity->User for clarity

### ISSUE THREAD

**Issue by marcua** [marcua/ayb#40]

**Comment by sofiaritz** [comment]
In the future things like organizations could be added, and this naming would be useful:
* Every user, bot account, organization, etc. is an Entity
* There are entities (like organizations) whose owner can only be a User or an Organization.
    * This allows things like sub-organizations to be created which can be useful in use cases like universities, where there is an organization for the Engineering department (which contains a CS suborg, a Mechanical Eng suborg, etc) and there is another organization for the Social Studies department (which contains a psychology suborg, an education suborg, etc).

I know this is just an implementation detail, but we should also have this in mind

**Comment by marcua** [comment]
Very nice! This makes me think I should close this issue out, given entities already have a type (user vs. organization) and we're now at N=2 that didn't find "Entity" to be too confusing a term :). I like your idea of entities owning entities in the future, and when we get there, that can be a foreign key/self-join on the `entity` table.

If you agree, I'll close this issue!

**Comment by sofiaritz** [comment]
> If you agree, I'll close this issue!
I agree, you can close the issue :)

**Comment by marcua** [comment]
Thank you @sofiaritz ! :)

**Comment by marcua** [comment]
Thank you @sofiaritz ! :)
